common: &common
  adapter: postgresql
  username:
  password:
  host: localhost
  timeout: 5000

development:
  <<: *common
  database: chimehack_dev

test:
  <<: *common
  database: chimehack_test

production:
  <<: *common
  database: chimehack
